### ISSUE TITLE
[Feature Request] Filtering of mods by enabled status

### ISSUE THREAD

**Issue by rikai** [Floogen/Stardrop#113]
Viewing what mods are enabled can be somewhat difficult if you have a large number of mods, it would be nice if there could be a filter that allows you to see only mods that are enabled. This would be useful for situations like profile comparisons to quickly see mod diferences.

I suppose this could also be used for other things, like only showing mods that are not enabled, or only showing mods that have updates

**Comment by Floogen** [comment]
If I am understanding your request correctly, this is already possible by utilizing the "Hide Disabled Mods" filter (located on the bottom left of the UI).

![image](https://user-images.githubusercontent.com/31755155/230694702-dc0fc61e-9bc3-4ed0-bffb-c8bd47a43dcc.png)

**Comment by rikai** [comment]
Omg, I totally missed that, I'm so sorry!

That's exactly what I meant. 👍
