### ISSUE TITLE
Stardrop doesn't launch

### ISSUE THREAD

**Issue by ArcaneDescent** [Floogen/Stardrop#12]
Stardrop simply refuses to launch now. I'm on the latest version currently, but so far it has only launched once, with the first version. Running as administrator also has no results

**Comment by Floogen** [comment]
I'll need more details to investigate this. If you can't get Stardrop to launch, the log can be discovered by going to `%APPDATA%\stardrop\Data\Logs`.

**Comment by ArcaneDescent** [comment]
[log.txt](https://github.com/Floogen/Stardrop/files/7795800/log.txt)
I was unaware Stardrop made logs, thanks!

**Comment by Floogen** [comment]
Could you test to see if v1.0.0-beta.11 resolves your issue?

If it doesn't, I'll need another log as I've included additional debugging information to help pinpoint this issue.

**Comment by ArcaneDescent** [comment]
That fixed it. Thank you!
