### ISSUE TITLE
Stardrop.sh doesn't run (Linux Mint 21.1 Cinnamon)

### ISSUE THREAD

**Issue by RealSnak3** [Floogen/Stardrop#120]
when i try to run Stardrop.sh nothing happens and i have Smapi installed i just don't understand what i'm doing wrong

https://github.com/Floogen/Stardrop/assets/109180957/8f03a1cc-3fb4-419d-bcbd-45bd15ea34ec

**Comment by Adda0** [comment]
Hey. Could you try to open a terminal and run the script from there? It would give us some output describing what went wrong.
Run
```sh
sh Stardrop.sh
```
or
```
./Stardrop.sh
```

And even better, could you run the following commands yourself (in the directory with the shell script):
```sh
chmod +x ./Internal
./Internal
```

**Comment by RealSnak3** [comment]
here the screen shot of the terminal sorry for the wait ISP was doing maintenance  
![20230604_031815](https://github.com/Floogen/Stardrop/assets/109180957/54c398c0-5d26-47b7-a2ec-715ba33f64de)

**Comment by RealSnak3** [comment]
also i tried both Nexus and Github downloads but the terminal pic is from Github

**Comment by Adda0** [comment]
No worries. Ahh, this problem again. See #90. This is a classic issue with running Stardrop on Linux. Basically, this uses an old version of some package called `libssl` and your distro has a newer one. You need to manually download the older version and install it. Let me know if you need more information than is provided in the related issue.
