### ISSUE TITLE
Fix linux install instructions link on gitbook

### ISSUE THREAD

**Issue by ghost** [Floogen/Stardrop#124]
On gitbook, the link for the linux instructions on this page: https://floogen.gitbook.io/stardrop/getting-started/installing-stardrop goes to https://floogen.gitbook.io/stardrop/getting-started/installing-stardrop/macos#instructions instead of https://floogen.gitbook.io/stardrop/getting-started/installing-stardrop/linux#instructions could you fix it please? Thank you!

**Comment by Floogen** [comment]
This has been fixed. Thank you for reporting this issue.
