### ISSUE TITLE
Please fix the odd text display problem on linux

### ISSUE THREAD

**Issue by sofiedotcafe** [Floogen/Stardrop#129]
I don't know why this happens (maybe related to system themes, using kde btw) 
![Screenshot_20230720_203415](https://github.com/Floogen/Stardrop/assets/122896463/765ed4db-cd37-4c2d-b18b-8b1af190284d)

**Comment by Adda0** [comment]
Hello. What is the problem here? That there is text inside the text boxes, but it is black and therefore cannot be seen? I do not think system themes can affect the styling here. Nevertheless, I cannot reproduce the issue on the latest Stardrop version. Is this still a problem for you?

**Comment by sofiedotcafe** [comment]
> Hello. What is the problem here? That there is text inside the text boxes, but it is black and therefore cannot be seen? I do not think system themes can affect the styling here. Nevertheless, I cannot reproduce the issue on the latest Stardrop version. Is this still a problem for you?

Can't reproduce anymore, I am no longer using KDE

**Comment by Adda0** [comment]
I cannot reproduce this issue even on KDE. I would consider the issue to be resolved until proven otherwise.
