### ISSUE TITLE
Smapi doesn't load mods above a certain amount through Stardrop

### ISSUE THREAD

**Issue by niassaem** [Floogen/Stardrop#14]
Hi! It's owlyandcattish from Nexusmods, I reported today the weird bug with the blank page. However, I've encountered the same issue others have reported: Smapi doesn't recognize mods through Stardrop. Specifically, there seems to be a cap perhaps on the amount of mods Stardrop tells Smapi to load as I didn't stumble into this problem with 18 mods.

I tried to be as thorough as possible and saved the logs of all three profiles I've created - Full ( 78 mods ), Vanilla Expanded ( 66 mods ) and Vanilla-friendly ( 18 mods ).

Full profile with 78 mods enabled, Stardrop + Smapi log - issue: zero mods are loaded, despite enabled
[FULL_profile_78_mods_log.txt](https://github.com/Floogen/Stardrop/files/7797097/FULL_profile_78_mods_log.txt)
https://smapi.io/log/f8e688cd76c743beacee7bda6a776f6f 

Vanilla Expanded with 66 mods enabled, Stardrop + Smapi log - issue: zero mods are loaded, despite enabled
[Expanded_66_mods_log.txt](https://github.com/Floogen/Stardrop/files/7797106/Expanded_66_mods_log.txt)
https://smapi.io/log/e72057d412c74f47b3a2c70c42da9b8d 

Vanilla-friendly with 18 mods enabled, Stardrop + Smapi log - no issues, mods loaded
[Vanilla_friendly_18_mods_log.txt](https://github.com/Floogen/Stardrop/files/7797113/Vanilla_friendly_18_mods_log.txt)
https://smapi.io/log/4730f23d527f4da7a1e337344e5d02e3 

For further context: I updated the mods I intended to play with today and I've also updated Stardrop before writing this report, currently I should be running the latest version that was uploaded to Nexusmods, but the issue remained. My selection of mods should all have their requirements and dependencies. My OS is Windows 10 Home and I'm running the latest Smapi build with the latest Stardew Valley version. Purchased through Steam, but ran it independently. 

Hope this helps and I managed to upload everything correctly. Let me know if you need any more information!

Edit: Decided to check what amount might be the limitation for Stardrop; first I enabled 30 mods and Smapi loaded them just fine. Same for 40 mods, however enabling 50 mods resulted in Smapi loading zero, so either Stardrop has a limitation starting at 50 or somewhere between 40 and 50 mods being enabled.

**Comment by sheetcakeghost** [comment]
https://smapi.io/log/04f0af0858a342509df6159faa3fa49f

I'm having the same issue. (sheetcakeghost on nexus) That is my log above. I haven't tested it with less mods, but I have over 500 (most of them tiny aesthetic mods, various NPCs and recipes, SVE, etc) being loaded. The logs for my other profiles don't give any new information.

**Comment by Floogen** [comment]
v1.0.0-beta.12 should hopefully resolve that issue.

Thank you for reporting this.

**Comment by sheetcakeghost** [comment]
Using .12 does seem to have resolved the issue.
