### ISSUE TITLE
Mac Version:The problem of unable to load mod remains unresolved

### ISSUE THREAD

**Issue by lilinonearth** [Floogen/Stardrop#15]
The new version is better than the previous version, but the pre mod of large mod cannot be loaded.
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/7797292/SMAPI-latest.txt)
[log.txt](https://github.com/Floogen/Stardrop/files/7797293/log.txt)

**Comment by Floogen** [comment]
Duplicate of #14
