### ISSUE TITLE
Linux version: Unable to load mods

### ISSUE THREAD

**Issue by irenegr** [Floogen/Stardrop#16]
Ubuntu 20.04
Stardrop 1.0.0-beta.11

[Smapi log](https://smapi.io/log/bbae6e11d60a4673b68517735be0cfdb)
[log.txt](https://github.com/Floogen/Stardrop/files/7797464/log.txt)

**Comment by Floogen** [comment]
Could you see if v1.0.0-beta.12 resolves this issue? If it doesn't, I'll need another set of log files.

**Comment by irenegr** [comment]
Still unable to load mods. 

[Smapi log](https://smapi.io/log/f1fce27d86824b3aba86fd74bfde0bd4)
[log1.txt](https://github.com/Floogen/Stardrop/files/7798650/log.txt)

smapi log and log after disabling 2 (problematic ?)  mods from the first log

[Smapi log](https://smapi.io/log/6695f004d654415d9d648c199d09d7ec)
[log2.txt](https://github.com/Floogen/Stardrop/files/7798661/log.txt)

**Comment by Floogen** [comment]
v1.0.0-beta.13 should hopefully resolve those issues.
