### ISSUE TITLE
Option to sort by downloaded time?

### ISSUE THREAD

**Issue by Kombwucha** [Floogen/Stardrop#160]
Hi! I apologize in advance if this is not the page to ask questions however I have been trying to find the filter/sort to find my mods via its downloaded date to see my most recent mods downloaded for Stardew. Hope I could gain some clarification if this feature is or is not available. Thank you!

**Comment by Adda0** [comment]
Hey. Sorry for late response. Stardrop currently does not store the date and time of downloading/updating a mod. I agree that such a feature could be useful, but it is not implemented as of now. Hopefully one day, someone will find the time to implement it.

**Comment by Floogen** [comment]
This feature was [implemented](https://github.com/Floogen/Stardrop/commit/bb695b035ae47776261364131b7c9bd4af4d3eab) a couple months ago.

I will see about getting a new build released this week, as the upcoming SDV v1.6 update is around the corner.

**Comment by Kombwucha** [comment]
Really? That's amazing, that would be super helpful. Thanks so much for the info!

**Comment by Kombwucha** [comment]
> This feature was [implemented](https://github.com/Floogen/Stardrop/commit/bb695b035ae47776261364131b7c9bd4af4d3eab) a couple months ago.
> 
> I will see about getting a new build released this week, as the upcoming SDV v1.6 update is around the corner.

May I know how do I download this build or update my stardrop to that specific update?

**Comment by Floogen** [comment]
Stardrop will notify you when a new version is available, after the application is opened. Otherwise you can download it manually on the [release page](https://github.com/Floogen/Stardrop/releases).

I will also be closing this issue when the new version is released, so you will be notified by GitHub as well.

**Comment by Floogen** [comment]
See the v1.0.0 release for the "Install Timestamp" and "Last Updated" columns!
