### ISSUE TITLE
SteamDeck Install Fails - Adda0 Flatpak

### ISSUE THREAD

**Issue by Punch-Tape-Boot** [Floogen/Stardrop#161]
(1)(deck@steamdeck Documents)$ flatpak install io.github.Adda0.Stardrop
Looking for matches...
error: No remote ref found for 'io.gethub.Adda0.Stardrop'

I also tried sudo with the same results.  I also did streamos-readonly disable.

**Comment by Adda0** [comment]
Hello. Firstly, this is not the right repository to file issues with StardropForked. The proper place is https://github.com/Adda0/Stardrop/issues, as pointed to by the Flatpak.

Second, the error here shows you mistyped `github` (you have `gethub` here). Is that the problem?

**Comment by Punch-Tape-Boot** [comment]
Thank you, and yep it appears to. If I have any other issues I'll use the github issue repository.

**Comment by Adda0** [comment]
Glad it works for you now. I consider this issue to be resolved. It can be closed.
