### ISSUE TITLE
Windows Flags as Malware

### ISSUE THREAD

**Issue by saphicstars** [Floogen/Stardrop#165]
I've been trying to install this for an hour and every time I attempt to tun Stardrop my antivirus immediately flags it as malware and won't allow me to open it. If I click 'run anyway', I just get a pop up stating that I may not have the right permissions to run this software. I don't have the option to run as administrator. I've tried so many different ways to get this to work.

**Comment by Floogen** [comment]
This sounds like an issue with your antivirus or a permission issue with your Windows account, not Stardrop specifically. I recommend researching what steps are required to allow software for your antivirus.

Regarding the malware statement, new releases of unsigned software can be flagged as such. Stardrop is open source, so you are free to review the code and compile it yourself.
