### ISSUE TITLE
"Broken: Compatability issue" listed on working mods

### ISSUE THREAD

**Issue by logwyrd** [Floogen/Stardrop#170]
Under Status, a bunch of mods are now showing "Broken: Compatibility Issue" when they are working fine and didn't have that text as of a few hours ago.

![image](https://github.com/Floogen/Stardrop/assets/126706946/9fd8826d-1c9a-408d-bb12-b5c1845ee73b)

**Comment by Floogen** [comment]
This is not an issue with Stardrop.

Stardrop pulls the list of compatible mods from [smapi.io](https://smapi.io/mods), which is a community maintained list of compatible mods (i.e. not maintained by Stardrop).
