### ISSUE TITLE
Mac version:More mods can be loaded, but a large number of mods cannot be loaded

### ISSUE THREAD

**Issue by lilinonearth** [Floogen/Stardrop#18]
The new version is much better, but I still can't load all mods.
[log.txt](https://github.com/Floogen/Stardrop/files/7798721/log.txt)
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/7798722/SMAPI-latest.txt)

**Comment by Floogen** [comment]
v1.0.0-beta.13 should workaround this issue.

For future note, you should be able to still comment on the closed issues that the problem is still occurring instead of making a new issue!
