### ISSUE TITLE
unable to open stardrop on mac

### ISSUE THREAD

**Issue by gkdistefano** [Floogen/Stardrop#187]
unable to open stardrop on mac 

https://smapi.io/log/24baff4fef124a3db2bc2f3265d18443<img width="402" alt="Screenshot 2024-04-14 at 4 16 22 PM" src="https://github.com/Floogen/Stardrop/assets/162777585/df4c2b82-ae86-4ee2-9776-9595cb3165dc">

**Comment by Floogen** [comment]
Please follow the [instructions for reporting issues](https://floogen.gitbook.io/stardrop/resources/reporting-issues) with Stardrop. I am unable to help without a log file.

**Comment by gkdistefano** [comment]
link has been added

**Comment by Floogen** [comment]
I may be missing something, but I only see the SMAPI link. I also need the Stardrop log file itself.

**Comment by gkdistefano** [comment]
how do i get the log file, it doesnt work when i do macOS\Users\USER_NAME_HERE\Stardrop\Data\Logs

**Comment by gkdistefano** [comment]
[log.txt](https://github.com/Floogen/Stardrop/files/14972192/log.txt)

is this it? i used /Users/username/.config/Stardrop/Data

**Comment by Floogen** [comment]
Thank you for noting the correct path. I have updated the macOS instructions for getting the log file, as it was missing `.config`.

And thank you for the log file, I am looking into it now.

**Comment by Floogen** [comment]
Hm, this issue seems like it may be unrelated to #185.

Could you [download](https://github.com/Floogen/Stardrop/releases/tag/v1.1.1-beta.4) and see if it resolves you issue?

**Comment by gkdistefano** [comment]
it seems to be working thank you for your help

**Comment by gkdistefano** [comment]
it seems to be working thank you for your help
