### ISSUE TITLE
Stardrop window still not appearing (version 1.1.1)

### ISSUE THREAD

**Issue by CrashyWashy** [Floogen/Stardrop#188]
added log file.

says something about not being able to perform  EGL-based rendering. more info in log below:

[log.txt](https://github.com/Floogen/Stardrop/files/14972660/log.txt)

**Comment by Floogen** [comment]
The EGL warning is not relevant, it has been a long standing issue with the Avalonia framework.

Could you try and see if [v1.1.2-beta.1](https://github.com/Floogen/Stardrop/releases/tag/v1.1.2-beta.1) resolves this issue?
