### ISSUE TITLE
Not working in Linux

### ISSUE THREAD

**Issue by ghost** [Floogen/Stardrop#20]
It's impossible to run on linux cause it's asking for StardewModdingAPI.exe file's location which is not present in linux. The file is `StardewValley`(with no extensions) but it doesn't show up when you browse to choose the file from the app.
When SMAPI file is installed in linux it renames itself to as `StardewValley` (with no extensions),so that steam would recognize it as the original launcher.
Also it's impossible to manually type/paste in the adress folder. you have to click the folder icon,but in the browse menu it doesn't show the `StardewValley` file.

**Comment by Floogen** [comment]
As explained #21, this is not true. `StardewModdingAPI` has to exist, as that is what the modified `StardewValley` executable uses to run. You can see this yourself by opening `StardewValley` in a text editor or look at SMAPI's [source code itself](https://github.com/Pathoschild/SMAPI/blob/develop/src/SMAPI.Installer/assets/unix-launcher.sh).

Below is a screenshot from Linux Mint.
![image](https://user-images.githubusercontent.com/31755155/147930812-e9bd9d42-6f2c-41db-a225-ca1665a495bf.png)

**Comment by ghost** [comment]
Alright. you are right. It exists. But still in the browse
menu it doesn't show files without extensions.

![Stardrop](https://user-images.githubusercontent.com/77489473/147940379-eba95ddf-f726-488d-8558-60d9d104b115.png)

**Comment by Floogen** [comment]
Hm, what distro is this? Linux Mint doesn't appear to have this problem.

As a workaround, I can look into making the textboxes editable for both paths.

**Comment by ghost** [comment]
It is Manjaro,which is based on Archlinux.

**Comment by Floogen** [comment]
I'll have a release later today that will workaround this issue by making both textboxes editable, allowing you to specify the path manually.

**Comment by ghost** [comment]
Thanks

**Comment by Floogen** [comment]
This should be resolved with v1.0.0-beta.15.
