### ISSUE TITLE
Cannot find separate config files for separate mod profiles

### ISSUE THREAD

**Issue by kalte-herz** [Floogen/Stardrop#225]
I have been using Stardrop quite a lot and I finally found the information that there can be separate config files for different profiles. I haven't been able to put this into practice. The major issue I've found this with is Tree Shaker 1.6 (https://www.nexusmods.com/stardewvalley/mods/23570) as I have one farm on the standard layout, and another with SVE's Grandpa's Farm. For these two, the location of the chest needs to be different. The config file is just a set of coordinates and it doesn't show up with Generic Config mod, so I have to go in and change the file myself.

I have the Enable Profile Specific Mod Configs option selected. However, I am unsure as to what "Mod config files are only saved and restored for enabled mods" means. Does this option only work if the mod is active on every profile? That isn't an option for me as I have a multiplayer profile that can't have it active. Am I missing something or is there something else I need to do to make this work?

**Comment by evanelric** [comment]
The profile specific configs aren't the ones in the mod folder when you use that feature, they're just the most recently active configs. Stardrop actually has its own json files that tell it how to apply the configs associated with each specific profile.

The easiest way to find them is View->Stardrop Log, which should open a folder (on windows mine leads to ...\AppData\Roaming\Stardrop\Data\Logs, if that helps you) and then you just navigate up one folder (to \AppData\Roaming\Stardrop\Data for me) and there is a folder in there called Profiles. Inside this folder is a json file for each profile that tells Stardrop how to run each mod that is _enabled_ for that specific profile, while it completely ignores config files for mods that _aren't_ enabled, which is what "Mod config files are only saved and restored for enabled mods" means.

So to change the chest location, you would have to open the json file that corresponds to the profile you want to change it in in a text editor (atom is pretty great, free, and open source, if you're looking for recs, but notepad will do in a pinch) and edit the portion of the json file that corresponds to the config file of the tree shaker mod. The contents of every config file for every enabled mod on that profile will all be listed out in that same json file, so using ctrl+f to look for the UniqueID from the mod's manifest.json could help if you have a lot of or lengthy config files.

**Comment by kalte-herz** [comment]
Found it! Thank you so much for your help
