### ISSUE TITLE
SMAPI not launching while using Stardrop

### ISSUE THREAD

**Issue by hartleybartley** [Floogen/Stardrop#28]
Hello, I am running into a problem where I can open and configure mods with Stardrop. However, when I run SMAPI via the Stardrop application, the program crashes and Stardew Valley does not load. I am able to run vanilla SDV via steam. 

My SMAPI Path is routed correctly to my SDV folder. Mods do not list any incompatibilities. I have included the Stardrop log below (SMAPI did not generate a log). Any tips? 

Thank you for your time!

[log.txt](https://github.com/Floogen/Stardrop/files/7836003/log.txt)

**Comment by Floogen** [comment]
I'll need some clarification. Does SMAPI crash or does Stardrop crash when running SMAPI via Stardrop?

If it is the former, SMAPI should definitely have created a log file and I'll need it to help further. Otherwise if it is Stardrop which crashes, I'll need a Stardrop log file from when it crashes (the one you attached doesn't have any crash data on it).

**Comment by hartleybartley** [comment]
So it looks like Stardrop closes completely. When I go to "View" -> "Stardrop Log File", the file report I attached previously is the only file available.

**Comment by Floogen** [comment]
Per the [documentation](https://floogen.gitbook.io/stardrop/resources/reporting-issues), you can find Stardrop's log at the following path if you are unable to start or access the application:
`%APPDATA%\stardrop\Data\Logs`

**Comment by hartleybartley** [comment]
[log.txt](https://github.com/Floogen/Stardrop/files/7836069/log.txt) - here is the only log in the folder. I uninstalled the game and SMAPI and re-installed and put the recommended pathway in for SMAPI. I was able to launch the game via steam with mods working correctly.  However, if I try to load throughout Stardrop, the application closes when I hit the launch SMAPI button.

But I am fine with using it to manage my mods and loading the game through Steam. Thank you for your time!

**Comment by Floogen** [comment]
Thank you for the log! I see the issue now.

It seems one of your mod configs isn't valid and Stardrop isn't handling the error correctly. I'll have an update out later today / tomorrow to resolve that issue.

Thank you again for reporting this issue!

**Comment by hartleybartley** [comment]
Oh I'm glad it was helpful! Thank you again for your time! Really loving the look of Stardrop.

Sent from the all new AOL app for Android 
 
  On Sun, Jan 9, 2022 at 4:32 PM, ***@***.***> wrote:   


Thank you for the log! I see the issue now.

It seems one of your mod configs isn't valid and Stardrop isn't handling the error correctly. I'll have an update out later today / tomorrow to resolve that issue.

Thank you again for reporting this issue!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
