### ISSUE TITLE
Mod Installation

### ISSUE THREAD

**Issue by Schn1ek3** [Floogen/Stardrop#31]
Is it possible when installing mods to create them without author in the mod folder? 
and save the config file so that it is preserved when reinstalling?

**Comment by Floogen** [comment]
I am unsure what you mean without an author in the mod folder. Could you explain that more?

Configs will automatically be restored the next time Stardrop detects the config, as Stardrop caches the settings via its profiles.

**Comment by Schn1ek3** [comment]
sorry, my mistake. it is not he author but the unique id. 
Mods that are installed via Stardrop are created like this:
Stardew Valley -> mods -> unique id -> mod

I personally prefer:
Stardew Valley -> Mods -> mod
Since I thought that you can set which folder path is created. So everyone can customize the way it is best for him.
For example:
Stardew Valley -> mods -> author -> mod
or
Stardew Valley -> mods -> author -> unique id -> mod

this is not so important, but could be interesting for one or the other.

__________________

I just tested again with the mod "timespeed" and the modconfig was not restored. The set times were set at the start of Smapi to the default values.

**Comment by Floogen** [comment]
Ah, you are referring to the output folder that Stardrop uses when installing new mods. I can look into adding a config setting to change the destination for installed mod.

As a note, most mods should install under the path `User Mod Folder -> Stardrop Installed Mods-> Mod Name`. UniqueID should only be used if the mod is improperly zipped (doesn't have a top level folder), in which case it will become `User Mod Folder -> Stardrop Installed Mods-> UniqueID`.

For the writing of the config, it appears Stardrop will only do it on the second run after SMAPI regenerates the file. I'll add a workaround for this Stardrop will reestablish the config if it has been deleted, before SMAPI runs.
