### ISSUE TITLE
Linux version: App crashing after a few seconds

### ISSUE THREAD

**Issue by irenegr** [Floogen/Stardrop#4]
OS: Ubuntu 20.04 64bit 
Kernel: 5.4.0-92-generic
Shell: bash
Stardrop version: 1.0.0-beta.8

[log.txt](https://github.com/Floogen/Stardrop/files/7791985/log.txt)

**Comment by Floogen** [comment]
Seems to be related to the framework itself https://github.com/AvaloniaUI/Avalonia/issues/7272, and the fix has yet to be released to a stable build.

Specifically it crashes after displaying a tooltip in Linux. I had already implemented a temporary workaround (by not displaying tooltips for Linux builds), but it appears the main menu one did not work. I'll have a patch out shortly!
