### ISSUE TITLE
Stardrop not detecting all mod updates

### ISSUE THREAD

**Issue by tlitookilakin** [Floogen/Stardrop#41]
Stardrop is not detecting updates for the following mods:

- Spacecore
- DGA
- JA
- GMCM
- Hybrid Crop Engine
- Content Patcher

[SMAPI log](https://smapi.io/log/a1304efb9f5549808df5076fc24cb8a9)
[Stardrop log](https://pastebin.com/CgbmcM9y)

**Comment by Floogen** [comment]
I was not able to replicate this issue with those mods, however I did add additional debug logging for when Stardrop checks for mod updates via smapi.io's API. Could you let me know if this issue still occurs after downloading v1.0.0-beta.23?
