### ISSUE TITLE
Missing dependency notification only when starting through the mod manager

### ISSUE THREAD

**Issue by erasels** [Floogen/Stardrop#5]
I have all the mods I'm currently playing with enabled via the enable all mods option in the tools window.

When starting via the normal method I don't get the below-shown error.

https://i.imgur.com/SfdxClI.png

**Comment by Floogen** [comment]
It is hard to tell without a log file, but it appears one of your normally hidden mods is being detected by Stardrop. Specifically a mod called "[PFM] Name of your pack".

The easy solution would be to disable that mod via Stardrop, though I am looking into adding an option to skip hidden mods.

Please refer to the [documentation on how to report issues](https://floogen.gitbook.io/stardrop/resources/reporting-issues).
