### ISSUE TITLE
Starting SMAPI with specific profile???

### ISSUE THREAD

**Issue by TrashMenagerie** [Floogen/Stardrop#52]
I can't figure out how to start the game with a specific profile? I'm sure I'm just missing something, but regardless, I can't figure it out. No matter what I try it just launches all of them.

**Comment by Floogen** [comment]
Please [follow the instructions found here](https://floogen.gitbook.io/stardrop/resources/reporting-issues) and return with the required log files, so that I may better help pinpoint any possible issues.

**Comment by TrashMenagerie** [comment]
Okay so sorry I didn't do that to begin with! 

Here's the SMAPI log file:
 https://smapi.io/log/42ab22c35a3b4b958a48c85693901fda

And here's the Stardrop log file:
[log.txt](https://github.com/Floogen/Stardrop/files/7946556/log.txt)

**Comment by Floogen** [comment]
There doesn't appear to be any issue from what I can see.

You mention that Stardrop "launches all of them", are you referring to the mods? If you only want certain mods to be enabled for your profile, simply deselect them (shown below as mods without checkmarks).

![image](https://user-images.githubusercontent.com/31755155/151378138-4a5ce33a-aead-4c75-bfe9-cd0ad6bb2e49.png)

**Comment by TrashMenagerie** [comment]
Once I have the ones I don't want deselected, do I just launch with the button in the top right corner? That's what I've been doing, but the game runs with all the mods rather than just the ones I have selected.

**Comment by Floogen** [comment]
Odd, could you test with the latest version (v1.0.0-beta.26) and let me know if the issue still occurs?

If the issue does still occur, I'll need another set of log files from you.
