### ISSUE TITLE
Stardew Valley Expanded is installing to the wrong folder?

### ISSUE THREAD

**Issue by soapisap** [Floogen/Stardrop#54]
[log.txt](https://github.com/Floogen/Stardrop/files/7994903/log.txt)
https://smapi.io/log/0d3b7a2da5b748b1b3e23c2b7f524863

Can't delete it and manually install using Stardrop either, or find it in the document folder.

**Comment by Floogen** [comment]
Hm, something is off here. Could you get me another Stardrop log after you run SMAPI via Stardrop?

**Comment by soapisap** [comment]
I fixed it manually by deleting stardew expanded and all of its
codepencencies without stardrop, then reinstalling also without stardrop.
Would a log of it now running regularly be useful still?

**Comment by Floogen** [comment]
I don't believe it'll be of much help now unfortunately. I will investigate installing SVE via Stardrop.

For now I'll be closing this issue as you resolved the problem.
