### ISSUE TITLE
Game restarting when loading a save

### ISSUE THREAD

**Issue by JohnMarley2021** [Floogen/Stardrop#6]
When launching the game with Stardrop, loading a save causes the game to restart, thus returning to the main menu.
Launching the game through Steam presents no issues.
Here's the SMAPI log : https://smapi.io/log/cd213064dd4041fcb0c431a5c396d050
Here's the Stardrop log :  [log.txt](https://github.com/Floogen/Stardrop/files/7792890/log.txt)

**Comment by Floogen** [comment]
It seems that you have two editions of PyTK that are being loaded. If I had to guess one of them is in a hidden folder which SMAPI by default ignores but Stardrop does. That would explain why it loads via Steam but not via Stardrop.

The simple solution would be to disable one of the PyTK versions in Stardrop, though I'll look into adding a warning for this situation.

![image](https://user-images.githubusercontent.com/31755155/147753261-94d3017e-8ee6-462d-9c96-0d994565b016.png)
