### ISSUE TITLE
Loading from Steam, Config files aren't saved

### ISSUE THREAD

**Issue by hub-bat** [Floogen/Stardrop#62]
When Stardrop is loaded using the steam launcher, it appears that the config files are reset to their default values. I'll either edit it using Generic Config Menu in-game, or out of game in the .json itself, but no matter what on Steam launch, the config isn't saved.

**Comment by Floogen** [comment]
Relates to #81

**Comment by Floogen** [comment]
v1.0.0-beta.34 should resolve this issue!
