### ISSUE TITLE
Stardrop Installed Mods Path doesn't exist?

### ISSUE THREAD

**Issue by bunnibri** [Floogen/Stardrop#65]
Setting up Stardrop for the first time with previously installed mods, gave the path to SMAPI.exe and it auto-filled the Stardrop Installed Mods Path to be:

/Users/brias/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS/Mods/Stardrop Installed Mods

When clicking 'save changes' I get this error box: The given Stardrop installed mods folder path doesn't exist. Reverting to previous path. 

I have no idea what this means sorry! I am not sure what I have done wrong but can't seem to find any answers to this elsewhere. Screenshots below. 

SMAPI log: https://smapi.io/log/c93f9c453e004b6599d8da6bf5f0
Stardrop log: [log.txt](https://github.com/Floogen/Stardrop/files/8503503/log.txt)

<img width="442" alt="Screen Shot 2022-04-18 at 4 34 43 PM" src="https://user-images.githubusercontent.com/103916878/163755505-3e93f210-f2e3-4e75-8a3c-5f934dc48b71.png">

<img width="442" alt="Screen Shot 2022-04-18 at 4 34 50 PM" src="https://user-images.githubusercontent.com/103916878/163755514-2de35e9f-e127-46b2-af02-986b099cf176.png">

**Comment by Crioware** [comment]
I had this problem on linux, and it has a decently simple fix. Under the ~/Stardew Valley/Mods create a folder called "Stardrop Installed Mods. Pic attached.

Hope this helps
![Screenshot_220419_00:44:12](https://user-images.githubusercontent.com/37206265/163942292-677aff56-3fc8-4f3c-9014-230bd388866e.png)
!

**Comment by bunnibri** [comment]
This worked a treat! Thanks so much :)

**Comment by Hollxzee** [comment]
When I installed Stardrop, Stardrop automatically made a folder entitled "Stardrop Installed Mods" but I'm still facing this issue. Does anyone have a different fix?

<img width="541" height="420" alt="Image" src="https://github.com/user-attachments/assets/f493ea74-bd92-42e2-b135-52fdace60882" />
