### ISSUE TITLE
Request - Select multiple files when adding mods

### ISSUE THREAD

**Issue by Crioware** [Floogen/Stardrop#66]
Title mostly says it all. I am currently adding a fair few mods to my game and adding them one at a time is quite tedious, this might be a decent addition to look at in the future. Thanks :)

**Comment by Floogen** [comment]
This is already possible by selecting multiple compressed mod folders, then utilizing the drag and drop method.

I have [updated the documentation](https://floogen.gitbook.io/stardrop/guides/using-stardrop/adding-a-mod) to include those details.
