### ISSUE TITLE
Scroll Issue

### ISSUE THREAD

**Issue by osonleffe** [Floogen/Stardrop#69]
When you scroll it will affect the spacing of items, occasionally moving the buttons off screen.

**Comment by Floogen** [comment]
I can't seem to replicate that issue, at least with items within the grid. Which buttons are you referring to?

I'll need your [Stardrop log](https://floogen.gitbook.io/stardrop/resources/reporting-issues) in order to help further.

**Comment by osonleffe** [comment]
It stopped, but it was annoying while it lasted.
