### ISSUE TITLE
requirements of requirements are ignored

### ISSUE THREAD

**Issue by Snaid1** [Floogen/Stardrop#7]
I'm testing out stardrop and wanted to try a profile that was just Ridgeside Village. when I started the game none of the mods loaded due to missing requirements of JsonAssets.

Steps to reproduce:
- have all appropriate mods installed on your system and all mods disabled (ridgeside village, json assets, spacecore, any other requirements needed for those mods)
- enable the ridgeside village mods
- attempt to start the game
- JSON Assets will be enabled but show in the "Skipped mods" section due to missing requirements (Spacecore) causing all ridgeside village mods to also appear there.

Expected behavior:
- when selecting a mod and it enables that mods requirements, it should check and enable the requirements of the required mods.

**Comment by Floogen** [comment]
This should be fixed with v1.0.0-beta.9.
