### ISSUE TITLE
Add the ability to update SMAPI

### ISSUE THREAD

**Issue by SinZ163** [Floogen/Stardrop#70]
With the introduction of Nexus Mod updating, along with the ability to self update Stardrop, what would complete the package is the ability to update SMAPI so everything can be done without leaving Stardrop.

I understand if installing SMAPI initially is out of scope, I'm mainly interested in updating an existing installation.

**Comment by Floogen** [comment]
This is doable, as SMAPI's releases can be fetched from the [releases page within its repository](https://github.com/Pathoschild/SMAPI/releases).

I've confirmed with Pathos that it is acceptable to download updates via this method, so I'll likely include this feature in the next major update. Note that this will only be for updating SMAPI, as Stardrop will still require SMAPI to be at least installed once.

As a note to myself, I'll need to link [SMAPI's release page]( https://smapi.io/release) in a pop-up after SMAPI is updated via Stardrop.

**Comment by Floogen** [comment]
This is now implemented in v1.0.0-beta.30. Thank you for the suggestion!
