### ISSUE TITLE
Wrong smapi.io URL for "Missing Requirements"

### ISSUE THREAD

**Issue by aracnus** [Floogen/Stardrop#75]
One of my installed mods have missing requirements (and I loved that Stardrop shows this!), but when I clicked on missing mod link, smapi.io show me nothing. So I noticed that its URL have a mistake. The original URL is:

https://smapi.io/mods#aedenthorn.ExtraMapLayers

but the correct one is:

https://smapi.io/mods#Extra_Map_Layers

And it happens with other missing mods either. smapi.io doesn't use the author id in URL. Another example, the correct id is "Custom_Companions" and not "PeacefulEnd.CustomCompanions".

**Comment by Floogen** [comment]
This only seems to occur when Stardrop can't reach smapi.io to perform the update check (which it also uses to check for the mod's actual name). In that situation it uses the mod's unique ID (which in this case is aedenthorn.ExtraMapLayers).

I'll keep this issue open for now, but it likely be closed in the future unless it proves to persist (e.g. it keeps happening even after Stardrop pulls smapi.io's updates).
