### ISSUE TITLE
Stardrop using disabled mods [Mac]

### ISSUE THREAD

**Issue by Kytthethief** [Floogen/Stardrop#77]
I've been using Stardrop for about 3 weeks now, and it consistently loads mods I've unchecked/disabled, rendering half the point of it useless for me. 

When I was messing with updates and troubleshooting last week, I _did_ get it to work properly!...For about a day. After my computer restarted the next day it was back to loading disabled mods again, and I've been unable to recreate whatever got it to temporarily work.

The mod I'm currently using to test whether they're loaded is Quality Smash.

[log.txt](https://github.com/Floogen/Stardrop/files/8748055/log.txt)
(not sure if the Smapi log would be helpful, since it appears as if loading the mod is normal for it)

**Comment by Floogen** [comment]
I just tested on my macOS environment and I am so far not able to replicate this issue. Your Stardrop log doesn't show Quality Smash as being one of the enabled mods, but without the SMAPI log I can't confirm what SMAPI is seeing.

Could I have the SMAPI log where this issue is happening, in addition to another Stardrop log?

**Comment by Kytthethief** [comment]
Certainly! 
[log.txt](https://github.com/Floogen/Stardrop/files/8748419/log.txt)
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/8748421/SMAPI-latest.txt)

**Comment by Floogen** [comment]
There is definitely something odd going on, as your SMAPI log shows that the mods are being loaded from your `.../steamapps/common/Stardew Valley/Contents/MacOS/Mods` when instead they should be loaded from your `/Users/USER_NAME/.config/Stardrop/Data/Selected Mods` folder.

If you go to the `/Users/USER_NAME/.config/Stardrop/Data/Selected Mods` folder, do you see any folders within there?

**Comment by Kytthethief** [comment]
Yes, it appears that my mods are in there (and no Quality Smash). Should I change the path(s) over to there?

**Comment by Floogen** [comment]
No, that path is managed by Stardrop. Something is wrong with how Stardrop is passing that path to SMAPI, but I am unable to replicate it with my macOS environment (Big Sur).

I'll have an update out shortly that may resolve this issue, but as I can't replicate the problem it may not actually fix it.

**Comment by Floogen** [comment]
Could you see if updating to v1.0.0-beta.33 resolves your issue?

**Comment by Kytthethief** [comment]
Apologies, Github emailed me last time you replied; I didn't get one this time.

Yes, I updated to beta.33 and it still seems to be acting up. 

[log.txt](https://github.com/Floogen/Stardrop/files/8792267/log.txt)
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/8792269/SMAPI-latest.txt)

Log Files again, just in case.

**Comment by Floogen** [comment]
Hello there! Could you see if v1.0.0-beta.34 resolves this issue?

Sorry for the long delay, my other projects have eaten up much of my time lately!

**Comment by Kytthethief** [comment]
Unfortunately it still seems to be an issue. Tried all sorts of variations of disabling and restarting and it loads my disabled mod (Quality Smash) regardless. Thanks for trying, though!

**Comment by lilynet336** [comment]
I just discovered Stardrop today and am also experiencing this issue. If it is not of priority to the maintainers of this project, especially after so long, I understand. Just thought I'd provide an update. I am on macOS Monterey 12.6.3, Stardrop 1.0.0-beta-36, SMAPI 3.18.2, Stardew Valley 1.5.6. I don't remember for sure, but I *think* that when I first ran the game through Stardrop, it didn't use the disabled mods, however it is consistently doing it now. Has anyone found a fix for this since then? Thank you all.

**Comment by daviewales** [comment]
I'm getting this too. (macOS 10.13.6).

**Comment by introducingtay** [comment]
I'm also encountering this, same pathing issue.

**Comment by lilynet336** [comment]
> I just discovered Stardrop today and am also experiencing this issue. If it is not of priority to the maintainers of this project, especially after so long, I understand. Just thought I'd provide an update. I am on macOS Monterey 12.6.3, Stardrop 1.0.0-beta-36, SMAPI 3.18.2, Stardew Valley 1.5.6. I don't remember for sure, but I _think_ that when I first ran the game through Stardrop, it didn't use the disabled mods, however it is consistently doing it now. Has anyone found a fix for this since then? Thank you all.

Just to update my comment, it doesn't do it every time, you just have to get lucky. If you need a workaround, run smapi with the `--mods-path` flag pointing to your mods folder, which is likely `~/.config/Stardrop/Data/Selected Mods`. If anyone needs help with the scripting please mention me and I can upload my command for running it.

**Comment by introducingtay** [comment]
> > I just discovered Stardrop today and am also experiencing this issue. If it is not of priority to the maintainers of this project, especially after so long, I understand. Just thought I'd provide an update. I am on macOS Monterey 12.6.3, Stardrop 1.0.0-beta-36, SMAPI 3.18.2, Stardew Valley 1.5.6. I don't remember for sure, but I _think_ that when I first ran the game through Stardrop, it didn't use the disabled mods, however it is consistently doing it now. Has anyone found a fix for this since then? Thank you all.
> 
> Just to update my comment, it doesn't do it every time, you just have to get lucky. If you need a workaround, run smapi with the `--mods-path` flag pointing to your mods folder, which is likely `~/.config/Stardrop/Data/Selected Mods`. If anyone needs help with the scripting please mention me and I can upload my command for running it.

I tried repathing by reinstalling SMAPI w the Stardrop path, but that didn't work; got an error about the SV executable not being in the folder. I am by no means a coding person, so is there another way to change the path? I used Stardop on my bf's gaming laptop before I got my Mac and I miss it lol

**Comment by lilynet336** [comment]
> > > I just discovered Stardrop today and am also experiencing this issue. If it is not of priority to the maintainers of this project, especially after so long, I understand. Just thought I'd provide an update. I am on macOS Monterey 12.6.3, Stardrop 1.0.0-beta-36, SMAPI 3.18.2, Stardew Valley 1.5.6. I don't remember for sure, but I _think_ that when I first ran the game through Stardrop, it didn't use the disabled mods, however it is consistently doing it now. Has anyone found a fix for this since then? Thank you all.
> > 
> > 
> > Just to update my comment, it doesn't do it every time, you just have to get lucky. If you need a workaround, run smapi with the `--mods-path` flag pointing to your mods folder, which is likely `~/.config/Stardrop/Data/Selected Mods`. If anyone needs help with the scripting please mention me and I can upload my command for running it.
> 
> I tried repathing by reinstalling SMAPI w the Stardrop path, but that didn't work; got an error about the SV executable not being in the folder. I am by no means a coding person, so is there another way to change the path? I used Stardop on my bf's gaming laptop before I got my Mac and I miss it lol

So basically, install Stardew Valley, SMAPI and Stardrop the normal way, and then when you want to open the game, *try* using Stardrop first, and if the mod count in the Title Bar of the game window looks *abnormal*, open a Terminal window and type or paste the code after this paragraph. You can also save it as a script so that you just have to double-click it. Do note that the path I used here is the default for Steam, if you installed a different way you can get the relevant path [here](https://stardewvalleywiki.com/Modding:Player_Guide/Getting_Started#Find_your_game_folder).

```bash
"~/Library/Application Support/Steam/steamapps/common/Stardew Valley.app/Contents/MacOS/StardewModdingAPI" --mods-path "~/.config/Stardrop/Data/Selected Mods"
```

If you (or anyone else viewing the issue) need some more help, I am happy to provide what I can.

**Comment by Floogen** [comment]
If either of you have log files (Stardrop and SMAPI) for when the issue occurs, that would greatly help! I just tested it with macOS Catalina, but I am still unable to replicate the issue.

Do either of you have steps to replicate the issue? Is it something that occurs every time you open Stardrop (without deselecting additional mods) or is it some other procedure?

I am hoping to squash some of the major outstanding bugs in the next few weeks and it would be nice to finally close this one out!

**Comment by lilynet336** [comment]
> If either of you have log files (Stardrop and SMAPI) for when the issue occurs, that would greatly help! I just tested it with macOS Catalina, but I am still unable to replicate the issue.
> 
> Do either of you have steps to replicate the issue? Is it something that occurs every time you open Stardrop (without deselecting additional mods) or is it some other procedure?
> 
> I am hoping to squash some of the major outstanding bugs in the next few weeks and it would be nice to finally close this one out!

I don't happen to have a log file at the moment, but the next time it happens I will grab mine. One question: at what point should I copy the log? Before quitting the app or after? I don't want to mis the chance and have it not happen for another while.

**Comment by Floogen** [comment]
Both options work, so long as you don't reopen Stardrop before copying the log file. Stardrop automatically clears out the old log once it starts up.

**Comment by lilynet336** [comment]
Good to know, thank you. I will update once it happens again.

**Comment by introducingtay** [comment]
> If either of you have log files (Stardrop and SMAPI) for when the issue occurs, that would greatly help! I just tested it with macOS Catalina, but I am still unable to replicate the issue.
> 
> Do either of you have steps to replicate the issue? Is it something that occurs every time you open Stardrop (without deselecting additional mods) or is it some other procedure?
> 
> I am hoping to squash some of the major outstanding bugs in the next few weeks and it would be nice to finally close this one out!

How do I grab a Stardrop log file? I know how to pull a Smapi log via the smapi.io but that’s the extent of my knowledge there

**Comment by Floogen** [comment]
The steps for both are listed [within the wiki](https://floogen.gitbook.io/stardrop/resources/reporting-issues).

More specifically go to `View` then `Log File`, which will open the location to your Stardrop log file.

**Comment by introducingtay** [comment]
[log.txt](https://github.com/Floogen/Stardrop/files/11024222/log.txt)
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/11024223/SMAPI-latest.txt)

**Comment by Floogen** [comment]
That is a good start, thank you!

Could you send over the Stardrop and SMAPI log after you press the run button or `Start SMAPI` option? The Stardrop log is missing some key information for what arguments it passes over to SMAPI.

There is no rush and thank you again.

**Comment by introducingtay** [comment]
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/11024654/SMAPI-latest.txt)
[log.txt](https://github.com/Floogen/Stardrop/files/11024657/log.txt)

Just ran it again and copied over the new logs. To my untrained eye, there aren't many differences other than me re-adding all the mods I moved out of my mods folder earlier today in an attempt to resolve this issue, but you'll know better than I. I just opened Stardrop and ran the profile for one of my saves, and according to the configs there should only be 137 selected mods for that profile, but 181 downloaded and available in the Mods folder. I did close the game at title screen, then went back to Stardrop to grab the logs; not sure if that means it'll be missing info you need

**Comment by Floogen** [comment]
It did have information I need, specifically it shows that Stardrop is attempting to pass your mod folder path over, but SMAPI is not receiving it (likely due to Stardrop passing it incorrectly).

Could you see if [v1.0.0-beta.36.1](https://github.com/Floogen/Stardrop/releases/tag/v1.0.0-beta.36.1) resolves your issue? You will need to manually download it, as it won't appear via Stardrop's update detection.

If this doesn't resolve it, I'll need to do some further testing.

**Comment by introducingtay** [comment]
Now Stardrop doesn't initiate SMAPI at all; I run SMAPI, Stardrop minimizes, but... nothing happens, not even an error message. If I go to open Stardom again, I get the standard "locked while SMAPI is running" message, but terminal isn't running and SMAPI isn't pulled up.

**Comment by Floogen** [comment]
That is odd! I'll need both log files again to help further, as they contain critical information for debugging.

**Comment by Floogen** [comment]
I see the issue now, I had passed the argument out of order when replacing the old method.

Could you see if [v1.0.0-beta.36.2](https://github.com/Floogen/Stardrop/releases/tag/v1.0.0-beta.36.2) resolves your issue? I'll need log files if the problem still persists.

**Comment by introducingtay** [comment]
That seems to have done the trick! I've only run it once, so if the issue returns later on I'll let you know a drop a new copy of my logs, but for now it seems to be resolved.
