### ISSUE TITLE
Mac version:Can't load mod 

### ISSUE THREAD

**Issue by lilinonearth** [Floogen/Stardrop#8]
My mother tongue is not English. There may be some problems.
I can't load mod in this way, but I can load it with steam.And I use this app on mac.
Thank you for your efforts.I like this mod very much.Is there any solution？
[log.txt](https://github.com/Floogen/Stardrop/files/7793668/log.txt)

**Comment by lilinonearth** [comment]
Just now I tried again and can successfully load mod. Is the app  unstable at some time?

**Comment by Floogen** [comment]
SMAPI seems to be loading without issue based on Stardrop's log, but I can't tell further without a log from SMAPI itself.

It appears your second run of SMAPI (in your log) ran for at least 4 minutes, so I am unsure what you mean by your mods not loading.

**Comment by lilinonearth** [comment]
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/7793741/SMAPI-latest.txt)

**Comment by Floogen** [comment]
Could you test v1.0.0-beta.9 and let me know if the issue still occurs? If it does, I'll need a new Stardrop and SMAPI log, as I've added additional debugging information.

**Comment by lilinonearth** [comment]
Sorry, I just read this message.I have upgraded the app to the latest version, the situation has improved, but only one mod has been loaded.
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/7795778/SMAPI-latest.txt)
[log.txt](https://github.com/Floogen/Stardrop/files/7795780/log.txt)

**Comment by Floogen** [comment]
I am not seeing SMAPI being started via Stardrop in the log. Could you get a log after clicking the run SMAPI button?

**Comment by lilinonearth** [comment]
[log.txt](https://github.com/Floogen/Stardrop/files/7796714/log.txt)

**Comment by Floogen** [comment]
v1.0.0-beta.11 should hopefully resolve your issue. Thank you for your help in debugging this issue!

If you are still having problems, please do let me know.
