### ISSUE TITLE
Stardrop Loading Mods I Disabled on MacOS

### ISSUE THREAD

**Issue by DTRW919** [Floogen/Stardrop#83]
Hello, I've come back to use Stardrop after a while, and it seems to continuously load mods I unchecked, which seems similar to #77. I'm using v1.0.0-beta.33, which seems to be the latest release, and I'm launching via Steam, my preferred way of launching the game.

[log.txt](https://github.com/Floogen/Stardrop/files/8934446/log.txt)
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/8934444/SMAPI-latest.txt)

The same thing happens when I launch via Stardrop

**Comment by Floogen** [comment]
Could you see if v1.0.0-beta.34 resolves your issue?

I am closing this issue to avoid duplicates, so please see #77 for further details if the latest release doesn't resolve the problem.
