### ISSUE TITLE
Enhancement Request - We should be able to have mod groupings for multi-part mods.

### ISSUE THREAD

**Issue by Snaid1** [Floogen/Stardrop#9]
Some larger mods have multiple sub-mods that are in the mods folder when you unzip the file. there should be a way to have mods that go together show as a group so they could be enabled/disabled together or at least be enabled without missing any.

Example mods this would apply to:
- Ridgeside Village
- Stardew Valley Expanded
- Zuzu City
- Walk to the Desert Redux
- many more!

**Comment by Floogen** [comment]
This technically would be resolved with https://github.com/Floogen/Stardrop/issues/7, assuming the mods with several sub-folders have their manifests set correctly.

**Comment by Floogen** [comment]
This should be fixed with v1.0.0-beta.9.
