### ISSUE TITLE
Install does not work, POP OS

### ISSUE THREAD

**Issue by LadyGrelka** [Floogen/Stardrop#90]
I am running POP OS 22.04 (Ubuntu flavor Linux)
I downloaded the Linux version from Nexus, extracted to my desktop, set the .sh file to  Allow executing file as program, right click .sh and click run as program, a window opens for like half a second and then closes. I then try to run from terminal and I get this

ladygrelka@pop-os:~/Desktop/Stardrop$ ./Stardrop.sh
No usable version of libssl was found
./Stardrop.sh: line 3: 172329 Aborted                 (core dumped) ./Internal

Any help fixing would be great.

**Comment by Adda0** [comment]
Hello, I remember that I had some problems with the Linux installation as well. In the end, I decided to just compile the source code myself. I bumped the dotnet version to 6.0 as I have dotnet 6.0 on my system (in `Stardrop/Stardrop.csproj`: `<TargetFramework>net6.0</TargetFramework>`) and run `dotnet build -c Release`. Then I start Stardrop with `Stardrop/bin/Release/Stardrop`.

However, in your case, it seems that you lack *libssl*. I would start with trying to figure out whether *libssl* is present on your system or to install/update *libssl* itself.

**Comment by LadyGrelka** [comment]
> 

Ok but what version of libssl, also I don't think its updated for POP OS 22.04, should I use an older version?

**Comment by Adda0** [comment]
Hard to tell from this. I would first try whichever is the newest one.

**Comment by LadyGrelka** [comment]
I don't even know what the newest version that works with POP OS is, its not on POP SHOP at all.

**Comment by Adda0** [comment]
That, I can understand. Let me check.

**Comment by itinerare** [comment]
So I just ran into this issue setting up on a laptop after having no trouble on my desktop, both running pop 22.04... Looks like the version that the desktop has but laptop lacks is `libssl1.1`.

**Comment by Adda0** [comment]
There are `libssl1.1` and `libssl3.0`. I am just setting up a Pop!_OS VM to see for myself. However, if it is indeed a `libssl1.1` which is needed. I would try to install it by running `sudo apt install libssl1.1` in the terminal. Otherwise, I would download one from Ubuntu or Debian repositories manually (`.deb` format) and install it. Will report back when I get Pop!_OS VM up and running.

**Comment by LadyGrelka** [comment]
> So I just ran into this issue setting up on a laptop after having no trouble on my desktop, both running pop 22.04... Looks like the version that the desktop has but laptop lacks is `libssl1.1`.

Might be a dumb question but I want to be sure, in order to install

**Comment by itinerare** [comment]
Yep, tested with manual install of `libssl1.1` (no wrangling it directly via apt it seems, but can be found [here](https://packages.ubuntu.com/impish/libssl1.1) as it stands) and no error now.

**Comment by LadyGrelka** [comment]
Umm there are 6 different downloads, not sure which one to get

**Comment by Adda0** [comment]
No worries. There are no dumb questions (possibly only dumb answers) :) Do you have AMD or Intel machine?

**Comment by LadyGrelka** [comment]
AMD Ryzen 5 5600x 6-core processor

**Comment by Adda0** [comment]
Then I would try [this one](https://packages.ubuntu.com/impish/amd64/libssl1.1/download).

**Comment by LadyGrelka** [comment]
Thanks!, It works.

**Comment by Adda0** [comment]
Great. Glad we have managed to figure it out. Have fun. Wish you all the best. Well, now that I have my VM ready, I might as well explore Pop!_OS a bit.

**Comment by Floogen** [comment]
Thank you @Adda0 and @itinerare for resolving this issue!

(Sorry I missed you there itinerare!)

**Comment by Adda0** [comment]
The same thanks go to @itinerare. It took me too long to set up the VM. Thanks to your fast testing and previous encounter with this problem, we have resolved the issue much faster. Have a good one.

**Comment by itinerare** [comment]
No problem, happy to help! Hope you all have a good one as well.
