### ISSUE TITLE
Stardrop won't install "Piper" mod

### ISSUE THREAD

**Issue by MadaraUchiha** [Floogen/Stardrop#91]
## Steps:
1. Set Stardrop as the handler for nexus mod manager download links
2. Go to [mod page](https://www.nexusmods.com/stardewvalley/mods/11283?tab=files)
3. Click "MOD MANAGER DOWNLOAD"

## Expected
1. Mod downloads after optionally asking for confirmation

## Actual
1. Stardrop asks for confirmation
2. Stardrop displays an error modal (screenshot below) saying it can't load the file.
3. Stardrop reports installation success, though the mod isn't found in the Stardrop mod list, or in the SDV Mods folder.

## Extras
Logfile: [log.txt](https://github.com/Floogen/Stardrop/files/9125871/log.txt)

The modal:
![image](https://user-images.githubusercontent.com/1188951/179357089-b0174d53-06f2-490e-bbd8-fc97b4ead403.png)

I suspect it's because the name has a quote in it, it has no issues with installing and updating any other mods for me.

**Comment by Floogen** [comment]
Fixed with Stardrop v1.0.0-beta.34. This was due to the mod having a __MACOSX folder.
