### ISSUE TITLE
Stardrop suddenly stopped working as intended

### ISSUE THREAD

**Issue by r4ddy** [Floogen/Stardrop#93]
I was installing mods for some time and everything went smoothly. At around 330 mods, when I tried replacing beta with main version of https://www.nexusmods.com/stardewvalley/mods/4582? stardrop just closed. After relaunching it suddenly it showed me that only 217 mods were enabled, search bar didn't work, when pressed "save configs" buttton, stardrop would crash again. Since then I was unable to get stardrop to working state again.

Down below I sent log file of stardrop.

[log.txt](https://github.com/Floogen/Stardrop/files/9193381/log.txt)

**Comment by Floogen** [comment]
Fixed with Stardrop v1.0.0-beta.34. This was due to the mod (NPC Adventures) having other files labelled "manifest.json" internally, which were not SMAPI structured files.

**Comment by r4ddy** [comment]
thank you for fixing it <3
