### ISSUE TITLE
No usable version of libssl was found - Fedora 36

### ISSUE THREAD

**Issue by aesouza98** [Floogen/Stardrop#94]
When I try to open the Stardrop.sh via the terminal, I get this error. 
Already installed openssl packages (that provide this lib), but it still won't work.

```
~/Downloads/Stardrop
❯ ./Stardrop.sh
No usable version of libssl was found
/home/adriano/Downloads/Stardrop/Stardrop.sh, linha 3: 14919 Abortado                (imagem do núcleo gravada)./Internal
```

**Comment by Floogen** [comment]
This likely relates to #90.

**Comment by aesouza98** [comment]
Thanks, reading through this Issue helped me clarify what libssl version is needed (it's 1.1), the openssl package provides the 3.0 version.
Installing `openssl1.1-devel` solved the issue.
