### ISSUE TITLE
[Suggestion] Detect mods updating to same version

### ISSUE THREAD

**Issue by LeFauxMatt** [Floogen/Stardrop#97]
Just thought of this now as when I click Install Update for Fashion Sense, the mod list refreshes, and it still says I need to update to Fashion Sense of the same version. Could Stardrop detect when the newest version downloaded is the same as what I already have, which is less than the version that the mod page indicates?

This helps if I am not paying much attention to the mods as I'm updating them, and unknowingly end up in a loop.

**Comment by Floogen** [comment]
This should be resolved with v1.0.0-beta.37. If it is not, please do let me know.
