### ISSUE TITLE
[PopOs] Stardrop can't find updates, nor connect to Nexus Mods API

### ISSUE THREAD

**Issue by Droppisalt** [Floogen/Stardrop#98]
Not sure if I'm doing anything wrong, but Stardrop doesn't seem to be able to access the internet. When I launch it, it gives me this screenshot:
![image](https://user-images.githubusercontent.com/67336980/186429041-2f9aba9c-fede-4204-819a-6571dd1efa75.png)

Looking for a SMAPI update gives this:
![image](https://user-images.githubusercontent.com/67336980/186429201-5dde6586-f69c-459b-86cc-851081c10baa.png)

Trying to add the Nexus Mods API also gives me an error

**Comment by Floogen** [comment]
Hm, could I see the Stardrop log file? It would help pinpoint why Stardrop is failing to reach the GitHub repository.

[Please see here](https://floogen.gitbook.io/stardrop/resources/reporting-issues) for steps on reporting issues.

**Comment by Droppisalt** [comment]
Sure, here it is
[log.txt](https://github.com/Floogen/Stardrop/files/9416649/log.txt)

and here's my [SMAPI log](https://smapi.io/log/446cf66a42964e8da66591e6e118131a)

**Comment by Droppisalt** [comment]
@Floogen any updates on this?

**Comment by rikai** [comment]
Based on the log, it looks like an SSL issue, specifically that the root certificate on your system doesn't trust the HTTPS URL.

Visiting [the api URL it's failing on](https://api.github.com/repos/Floogen/Stardrop/releases/latest) has no SSL warnings for me, however, which might indicate something to do with the certificate chain on your system?

**Comment by Droppisalt** [comment]
Forgot to update this thread, but a month or 2 ago it started working. Didn't change anything on my part, so maybe an update of my OS fixed it.

Good to know it might've been that. If it comes back, I'll know where to look
